### PR TITLE
Limit length of tag names

### PR DESCRIPTION
**Pull request by alamais-df**
Add limits on tag name lengths, both frontend and backend.

### CODE REVIEW

**Comment by Belomi** [comment]
What are the benefits of a quiet truncation of longer tags over just showing an error message? If anything I think that a message stating that truncation has occurred may be a better solution than simply doing it quietly.

**Comment by basisbit** [comment]
@Belomi afaik, @alamais-df wanted that someone adds the frontend part for showing the user that a tags are too long, and maybe automatically truncate them. That is the reason for why this PR is still a draft and not yet ready to be merged. If you have the free time to implement, please help out and create a pull request for the frontend / javascript code changes.

**Comment by basisbit** [comment]
If no one is working on this, I'd suggest we merge this already and create a new issue for the frontend part?

**Comment by alamais-df** [comment]
It does work as-is to prevent craziness, just isn't user-friendly.  If long tags have become a problem, this is probably better than nothing.

**Pull request merged**
