### PR TITLE
Add limitations on names, using new phoenix auth from philomena-dev.

### PR DESCRIPTION
**Pull request by alamais-df**
- Merges in new phoenix-based authentication system from philomena-dev, with required email verification.
 - Adds two new Plugs:
   - NotableNamePlug with associated backing functions and DB table schema, which will block registration or changing to any name in the notable_names table, if it exists. Code relies on the presence of postgresql helper functions and a trigger that process names both on insert and query, removing punctuation and spaces, and downcasing. Scripts added to root dir that create the notable_names table and its associated functions and insert trigger, and insert a small set of test names. Admins and moderators with user management permissions are able to change user's names to restricted names.
   - NameLengthLimiterPlug, which...limits the lengths of names (to 80 characters max).
- Modifies RegistrationController to use new plugs on user creation.
- Modifies NameController to use new plugs on user name change.

### CODE REVIEW

**Comment by basisbit** [comment]
@liamwhite can you please resolve the merge conflicts?

**Comment by basisbit** [comment]
@alamais-df Can you please resolve the merge conflicts?

**Comment by basisbit** [comment]
Uh, actually, this pull request comtains a bunch of commits which were already applied in our repository and a bunch of commits which are unrelated to this PR

**Comment by alamais-df** [comment]
Ugh, I fail at git, esp. with pulling over from philomena-dev.  I'll try to figure it out.

**Pull request closed without merging**
